<a href="https://colab.research.google.com/github/marcinwolter/NumericalAnalysis2020/blob/master/lab6_gaussian_elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Gaussian elimination

import scipy 
import scipy.linalg
import numpy as np
import copy

def linearsolver(A,b):
  n = len(A)
  M = A

  i = 0
  for x in M:
   x.append(b[i])
   i += 1


  for k in range(n):
   # first pivoting
   for i in range(k,n):
     if abs(M[i][k]) > abs(M[k][k]):
        M[k], M[i] = M[i],M[k]
     else:
        pass
   
   # Gaussian elimination in loop 
   for j in range(k+1,n):
       q = float(M[j][k]) / M[k][k]
       for m in range(k, n+1):
          # M_jm = M_jm - M_jk / M_kk *M_km
          M[j][m] -=  q * M[k][m]

  x = [0 for i in range(n)]       # x = [0, 0, .... , 0]

  # calculating x
  x[n-1] =float(M[n-1][n])/M[n-1][n-1]
  for i in range (n-1,-1,-1):
    z = 0
    for j in range(i+1,n):
        z = z  + float(M[i][j])*x[j]
    x[i] = float(M[i][n] - z)/M[i][i]
  return x


A = [[2, 1, 1, 0], [4, 3, 3, 1], [8, 7, 9, 5], [6, 7, 9, 8]]
b = [1, 2, 3, 4]

A1 = copy.deepcopy(A)
x = linearsolver(A1, b)

print("Result with our linearsolver:")
print(np.array(A)," * x = ",np.array(b))
print("Solution:")
print(x)




x = scipy.linalg.solve(A,b)

print(" ")
print("Result with linalg.solve:")
print(np.array(A)," * x = ",np.array(b))
print("Solution:")
print(x)


Result with our linearsolver:
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]  * x =  [1 2 3 4]
Solution:
[0.9999999999999993, 0.5000000000000008, -1.4999999999999998, 0.9999999999999997]
 
Result with linalg.solve:
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]  * x =  [1 2 3 4]
Solution:
[ 1.   0.5 -1.5  1. ]
